#!/bin/bash

filename=$1
scriptName=$filename.QScript
if [ -s $filename ]
then
    (
	echo "#!/bin/bash"
    cat $HOME/bash.scripts/YNQ.func
    while read line
    do
	echo "echo"
	echo "echo '=============================='"
	lineNoQuotes=$(echo "$line" |
		      sed -e "s,','\\'',g")
	escLine=$(echo "$line" |
		      sed  \
			  -e 's,",\\",g' \
			  -e "s,','\\'',g" \
			  -e 's,\$(,\\$(,'
			  )
	echo "echo \"Command:\" '$lineNoQuotes'"
	echo "YNQ 'Execute' \"$escLine\""
    done
    ) > $scriptName < $filename
    chmod +x $scriptName

    echo Created $scriptName
else
    echo $filename does not exist
    exit 1
fi
