#!/bin/bash

. $HOME/bash.scripts/YNQ.func

updates=$(go list -m -u all  | grep ']$')
if [ $(echo $updates | wc -l) == 0 ]
then
    echo "Nothing to update"
    exit 0
fi

shout.smallHeader "available updates"
echo $updates

for upd in $(echo $updates | sed -e 's/ v.* \[/@/' -e 's/\]$//')
do
    YNQ "update module to $upd" go mod edit -require $upd
done
